---
- name: Test with persistent proof (no facts)
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get current timestamp
      command: date '+%Y-%m-%d %H:%M:%S'
      register: current_time

    - name: Create file in /tmp
      copy:
        content: "AWX Success! Created at {{ current_time.stdout }}"
        dest: /tmp/awx-success.txt

    - name: Show file was created
      command: cat /tmp/awx-success.txt
      register: file_content

    - name: Display file content in AWX logs
      debug:
        msg: "File content: {{ file_content.stdout }}"

    - name: Verify file exists
      stat:
        path: /tmp/awx-success.txt
      register: file_stat

    - name: Show file stats
      debug:
        msg: "File exists: {{ file_stat.stat.exists }}, Size: {{ file_stat.stat.size | default('N/A') }}"

    - name: List /tmp contents to confirm
      command: ls -la /tmp/awx-success.txt
      register: file_listing

    - name: Show file listing
      debug:
        msg: "{{ file_listing.stdout }}"