---
- name: Test with persistent proof
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create file in /tmp
      copy:
        content: "AWX Success! Created at {{ ansible_date_time.iso8601 }}"
        dest: /tmp/awx-success.txt

    - name: Show file was created
      command: cat /tmp/awx-success.txt
      register: file_content

    - name: Display file content in AWX logs
      debug:
        msg: "File content: {{ file_content.stdout }}"

    - name: Verify file exists
      stat:
        path: /tmp/awx-success.txt
      register: file_stat

    - name: Show file stats
      debug:
        msg: "File exists: {{ file_stat.stat.exists }}, Size: {{ file_stat.stat.size | default('N/A') }}"