---
- name: Basic AWX Test
  hosts: all
  gather_facts: yes
  tasks:
    - name: Check current directory
      command: pwd
      register: current_dir
    
    - name: Show current directory
      debug:
        msg: "Current directory: {{ current_dir.stdout }}"
    
    - name: List files in /tmp
      command: ls -la /tmp
      register: tmp_files
    
    - name: Show tmp files
      debug:
        msg: "{{ tmp_files.stdout_lines }}"
    
    - name: Create file in /tmp (no sudo needed)
      file:
        path: /tmp/awx-success.txt
        state: touch
        mode: '0644'
    
    - name: Write content to file
      copy:
        content: "AWX Test Successful!\nTimestamp: {{ ansible_date_time.iso8601 }}"
        dest: /tmp/awx-success.txt