# Configures detailed logging, metrics and monitoring for all processes 
- name: 'Monitoring'
  hosts: all
  become: true
  tags: monitoring
  
  tasks:
    - include_role:
        name: monit
      when: monit_enabled | default(true)
      tags: [ monit ]
      ignore_errors: true

    - include_role:
        name: logrotate
      when: logrotate_enabled | default(true)
      tags: [ logrotate ]
      ignore_errors: true

    - include_role:
        name: loki
      when: loki_enabled | default(true)
      tags: [ loki ]
      ignore_errors: true

    - include_role:
        name: grafana-agent
      when: grafana_agent_enabled | default(true)
      tags: [ grafana-agent ]
      ignore_errors: true

    - include_role:
        name: blackbox_exporter
      when: blackbox_exporter_enabled | default(true)
      tags: [ blackbox_exporter ]
      ignore_errors: true

    - include_role:
        name: node_exporter
      when: node_exporter_enabled | default(true)
      tags: [ node_exporter ]
      ignore_errors: true

    - include_role:
        name: prometheus
      when: prometheus_enabled | default(true)
      tags: [ prometheus ]
      ignore_errors: true

    - include_role:
        name: grafana
      when: grafana_enabled | default(true)
      tags: [ grafana ]
      ignore_errors: true
